### ISSUE TITLE
Bug: Outbound Cache exceeds the localstorage quota

### ISSUE THREAD

**Issue by HiptJo** [HiptJo/active-connect-ng2#2]
**Describe the bug**
When large amount of data is stored within the cache, an exception is thrown and the data is not accessible via the Outbound getter.

```
Failed to execute 'setItem' on 'Storage': Setting the value of 'ac_oc_aid.aid' exceeded the quota.
core.mjs:8506 ERROR DOMException: Failed to execute 'setItem' on 'Storage': Setting the value of 'ac_oc_aid.aid' exceeded the quota.
    at setOutbound (http://localhost:4200/vendor.js:91766:24)
    at ApplicationPool.messageReceived (http://localhost:4200/vendor.js:91561:13)
    at ws.onmessage [as __zone_symbol__ON_PROPERTYmessage] (http://localhost:4200/vendor.js:91479:12)
    at WebSocket.wrapFn (http://localhost:4200/polyfills.js:8023:35)
    at _ZoneDelegate.invokeTask (http://localhost:4200/polyfills.js:7665:171)
    at http://localhost:4200/vendor.js:69233:49
    at AsyncStackTaggingZoneSpec.onInvokeTask (http://localhost:4200/vendor.js:69233:30)
    at _ZoneDelegate.invokeTask (http://localhost:4200/polyfills.js:7665:54)
    at Object.onInvokeTask (http://localhost:4200/vendor.js:69535:25)
    at _ZoneDelegate.invokeTask (http://localhost:4200/polyfills.js:7665:54)
```

**Comment by HiptJo** [comment]
indexedDb can be used to increase the cache size.
